#include<iostream>
#include<string>
#include<vector>
using namespace std;

struct player{
    string name;
    string position;
    int power;
};

int main()

{

vector<player> FW = {     // กองหน้า
    { "Mohamed Salah",         "FW", 91 },
    { "Alexander Isak",        "FW", 88 },
    { "Hugo Ekitiké",          "FW", 83 },
    { "Cody Gakpo",            "FW", 84 },
    { "Federico Chiesa",       "FW", 81 },
    { "Viktor Gyökeres",       "FW", 87 },
    { "Leandro Trossard",      "FW", 83 },
    { "Kai Havertz",           "FW", 82 },
    { "Gabriel Martinelli",    "FW", 81 },
    { "Noni Madueke",          "FW", 80 },
    { "Gabriel Jesus",         "FW", 80 },
    { "Erling Haaland",        "FW", 90 },
    { "Omar Marmoush",         "FW", 84 },
    { "Phil Foden",            "FW", 85 },
    { "Savinho",               "FW", 82 },
    { "Rayan Cherki",          "FW", 81 },
    { "Jérémy Doku",           "FW", 80 },
    { "Oscar Bobb",            "FW", 72 },
    { "João Pedro",            "FW", 79 },
    { "Liam Delap",            "FW", 78 },
    { "Raheem Sterling",       "FW", 78 },
    { "Pedro Neto",            "FW", 77 },
    { "Estêvão",               "FW", 78 },
    { "Jamie Gittens",         "FW", 78 },
    { "Bryan Mbeumo",          "FW", 85 },
    { "Benjamin Šeško",        "FW", 80 },
    { "Joshua Zirkzee",        "FW", 77 },
    { "Anthony Gordon",        "FW", 83 },
    { "Yoane Wissa",           "FW", 82 },
    { "Jacob Murphy",          "FW", 81 },
    { "Anthony Elanga",        "FW", 81 },
    { "Harvey Barnes",         "FW", 80 },
    { "Nick Woltemade",        "FW", 79 },
    { "Jacob Ramsey",          "FW", 78 },
    { "Ollie Watkins",         "FW", 84 },
    { "John McGinn",           "FW", 81 },
    { "Evann Guessand",        "FW", 79 },
    { "Donyell Malen",         "FW", 79 },
    { "Jadon Sancho",          "FW", 80 },
    { "Brian Brobbey",         "FW", 77 },
    { "Simon Adingra",         "FW", 76 },
    { "Bertrand Traoré",       "FW", 75 },
    { "Chemsdine Talbi",       "FW", 73 },
    { "Wilson Isidor",         "FW", 72 },
    { "Eliezer Mayenda",       "FW", 71 },
    { "Romaine Mundle",        "FW", 71 },
    { "Abdoullah Ba",          "FW", 70 },
    { "Ian Poveda",            "FW", 70 },
    { "Jack Grealish",         "FW", 80 },
    { "Illiman Ndiaye",        "FW", 79 },
    { "Dwight McNeil",         "FW", 78 },
    { "Thierno Barry",         "FW", 77 },
    { "Beto",                  "FW", 76 },
    { "Tyler Dibling",         "FW", 74 },
    { "Randal Kolo Muani",     "FW", 81 },
    { "Mohammed Kudus",        "FW", 80 },
    { "Dominic Solanke",       "FW", 80 },
    { "Brennan Johnson",       "FW", 79 },
    { "Richarlison",           "FW", 78 },
    { "Mathys Tel",            "FW", 77 },
    { "Wilson Odobert",        "FW", 75 },
    { "Dane Scarlett",         "FW", 70 },
    { "Dejan Kulusevski",      "FW", 83 },
    { "Alex Iwobi",            "FW", 80 },
    { "Samuel Chukwueze",      "FW", 80 },
    { "Raúl Jiménez",          "FW", 77 },
    { "Adama Traoré",          "FW", 75 },
    { "Harry Wilson",          "FW", 76 },
    { "Kevin",                 "FW", 76 },
    { "Rodrigo Muniz",         "FW", 75 },
    { "Kaoru Mitoma",          "FW", 82 },
    { "Danny Welbeck",         "FW", 78 },
    { "Yankuba Minteh",        "FW", 77 },
    { "Solly March",           "FW", 75 },
    { "Charalampos Kostoulas", "FW", 72 },
    { "Stefanos Tzimas",       "FW", 72 },
    { "Tom Watson",            "FW", 70 },
    { "Jean-Philippe Mateta",  "FW", 82 },
    { "Yeremy Pino",           "FW", 80 },
    { "Chrisantus Uche",       "FW", 76 },
    { "Eddie Nketiah",         "FW", 74 },
    { "Jesurun Rak-Sakyi",     "FW", 72 },
    { "Romain Esse",           "FW", 70 },
    { "Kevin Schade",          "FW", 78 },
    { "Dango Ouattara",        "FW", 77 },
    { "Reiss Nelson",          "FW", 75 },
    { "Igor Thiago",           "FW", 75 },
    { "Myles Peart-Harris",    "FW", 70 },
    { "Gustavo Nunes",         "FW", 70 },
    { "Antoine Semenyo",       "FW", 80 },
    { "Evanilson",             "FW", 80 },
    { "Amine Adli",            "FW", 78 },
    { "Enes Ünal",             "FW", 77 },
    { "Marcus Tavernier",      "FW", 76 },
    { "Romain Faivre",         "FW", 76 },
    { "David Brooks",          "FW", 75 },
    { "Eli Junior Kroui",      "FW", 74 },
    { "Ben Doak",              "FW", 71 },
    { "Bukayo Saka",           "FW", 88 }
};


vector<player> MF = {     // กองกลาง
    { "Florian Wirtz",         "MF", 89 },
    { "Alexis Mac Allister",   "MF", 87 },
    { "Ryan Gravenberch",      "MF", 85 },
    { "Dominik Szoboszlai",    "MF", 83 },
    { "Curtis Jones",          "MF", 80 },
    { "Wataru Endo",           "MF", 80 },
    { "Declan Rice",           "MF", 87 },
    { "Martin Ødegaard",       "MF", 87 },
    { "Mikel Merino",          "MF", 83 },
    { "Zubimendi",             "MF", 83 },
    { "Eberechi Eze",          "MF", 83 },
    { "Rodri",                 "MF", 90 },
    { "Tijjani Reijnders",     "MF", 86 },
    { "Bernardo Silva",        "MF", 84 },
    { "Mateo Kovačić",         "MF", 83 },
    { "Nico González",         "MF", 79 },
    { "Kalvin Phillips",       "MF", 74 },
    { "Cole Palmer",           "MF", 87 },
    { "Moisés Caicedo",        "MF", 87 },
    { "Enzo Fernández",        "MF", 84 },
    { "Andrey Santos",         "MF", 80 },
    { "Romeo Lavia",           "MF", 78 },
    { "Alejandro Garnacho",    "MF", 77 },
    { "Dário Essugo",          "MF", 75 },
    { "Bruno Fernandes",       "MF", 87 },
    { "Matheus Cunha",         "MF", 83 },
    { "Casemiro",              "MF", 80 },
    { "Manuel Ugarte",         "MF", 79 },
    { "Amad Diallo",           "MF", 79 },
    { "Kobbie Mainoo",         "MF", 77 },
    { "Mason Mount",           "MF", 77 },
    { "Bruno Guimarães",       "MF", 86 },
    { "Sandro Tonali",         "MF", 86 },
    { "Joelinton",             "MF", 82 },
    { "Joe Willock",           "MF", 76 },
    { "Youri Tielemans",       "MF", 85 },
    { "Boubacar Kamara",       "MF", 83 },
    { "Morgan Rogers",         "MF", 82 },
    { "Amadou Onana",          "MF", 79 },
    { "Harvey Elliott",        "MF", 78 },
    { "Emiliano Buendía",      "MF", 77 },
    { "Ross Barkley",          "MF", 77 },
    { "Granit Xhaka",          "MF", 85 },
    { "Habib Diarra",          "MF", 77 },
    { "Enzo Le Fée",           "MF", 76 },
    { "Noah Sadiki",           "MF", 74 },
    { "Dan Neil",              "MF", 73 },
    { "Chris Rigg",            "MF", 70 },
    { "Idrissa Gueye",         "MF", 79 },
    { "Kiernan Dewsbury-Hall", "MF", 77 },
    { "James Garner",          "MF", 76 },
    { "Carlos Alcaraz",        "MF", 75 },
    { "Merlin Röhl",           "MF", 74 },
    { "Tim Iroegbunam",        "MF", 74 },
    { "Xavi Simons",           "MF", 84 },
    { "James Maddison",        "MF", 84 },
    { "João Palhinha",         "MF", 83 },
    { "Rodrigo Bentancur",     "MF", 80 },
    { "Pape Matar Sarr",       "MF", 79 },
    { "Yves Bissouma",         "MF", 78 },
    { "Lucas Bergvall",        "MF", 77 },
    { "Archie Gray",           "MF", 75 },
    { "Sander Berge",          "MF", 79 },
    { "Saša Lukić",            "MF", 78 },
    { "Emile Smith Rowe",      "MF", 77 },
    { "Tom Cairney",           "MF", 74 },
    { "Harrison Reed",         "MF", 72 },
    { "Josh King",             "MF", 70 },
    { "Carlos Baleba",         "MF", 81 },
    { "Mats Wieffer",          "MF", 78 },
    { "Georginio Rutter",      "MF", 77 },
    { "Jack Hinshelwood",      "MF", 75 },
    { "Yasin Ayari",           "MF", 75 },
    { "Brajan Gruda",          "MF", 74 },
    { "Diego Gómez",           "MF", 73 },
    { "James Milner",          "MF", 73 },
    { "Adam Wharton",          "MF", 79 },
    { "Ismaïla Sarr",          "MF", 79 },
    { "Jefferson Lerma",       "MF", 77 },
    { "Daichi Kamada",         "MF", 77 },
    { "Cheick Doucouré",       "MF", 77 },
    { "Will Hughes",           "MF", 77 },
    { "Justin Devenny",        "MF", 71 },
    { "Naouirou Ahamada",      "MF", 70 },
    { "Mikkel Damsgaard",      "MF", 80 },
    { "Jordan Henderson",      "MF", 79 },
    { "Mathias Jensen",        "MF", 77 },
    { "Vitaly Janelt",         "MF", 76 },
    { "Frank Onyeka",          "MF", 74 },
    { "Fábio Carvalho",        "MF", 74 },
    { "Antoni Milambo",        "MF", 73 },
    { "Yehor Yarmoliuk",       "MF", 71 },
    { "Ryan Christie",         "MF", 79 },
    { "Tyler Adams",           "MF", 79 },
    { "Lewis Cook",            "MF", 79 },
    { "Justin Kluivert",       "MF", 79 },
    { "Alex Scott",            "MF", 74 }
};

vector<player> DF = {    // กองหลัง
    { "Virgil van Dijk",       "DF", 90 },
    { "Ibrahima Konate",       "DF", 86 },
    { "Jeremie Frimpong",      "DF", 83 },
    { "Andrew Robertson",      "DF", 82 },
    { "Joe Gomez",             "DF", 79 },
    { "Milos Kerkez",          "DF", 82 },
    { "William Saliba",        "DF", 88 },
    { "Benjamin White",        "DF", 83 },
    { "Jurrien Timber",        "DF", 82 },
    { "Riccardo Calafiori",    "DF", 78 },
    { "Gabriel Magalhaes",     "DF", 88 },
    { "Lewis-Skelly",          "DF", 78 },
    { "Ruben Dias",            "DF", 86 },
    { "Josko Gvardiol",        "DF", 84 },
    { "Nathan Ake",            "DF", 83 },
    { "John Stones",           "DF", 82 },
    { "Rico Lewis",            "DF", 77 },
    { "Abdukodir Khusanov",    "DF", 77 },
    { "Marc Cucurella",        "DF", 84 },
    { "Reece James",           "DF", 81 },
    { "Levi Colwill",          "DF", 80 },
    { "Malo Gusto",            "DF", 79 },
    { "Trevoh Chalobah",       "DF", 79 },
    { "Wesley Fofana",         "DF", 79 },
    { "Axel Disasi",           "DF", 77 },
    { "Tosin Adarabioyo",      "DF", 78 },
    { "Matthijs de Ligt",      "DF", 82 },
    { "Lisandro Martinez",     "DF", 81 },
    { "Noussair Mazraoui",     "DF", 80 },
    { "Harry Maguire",         "DF", 80 },
    { "Diogo Dalot",           "DF", 79 },
    { "Luke Shaw",             "DF", 79 },
    { "Leny Yoro",             "DF", 78 },
    { "Tyrell Malacia",        "DF", 77 },
    { "Fabian Schar",          "DF", 82 },
    { "Sven Botman",           "DF", 82 },
    { "Kieran Trippier",       "DF", 80 },
    { "Lewis Hall",            "DF", 80 },
    { "Tino Livramento",       "DF", 80 },
    { "Dan Burn",              "DF", 79 },
    { "Ezri Konsa",            "DF", 82 },
    { "Lucas Digne",           "DF", 80 },
    { "Pau Torres",            "DF", 80 },
    { "Ian Maatsen",           "DF", 79 },
    { "Matty Cash",            "DF", 79 },
    { "Tyrone Mings",          "DF", 78 },
    { "Reinildo Mandava",      "DF", 79 },
    { "Nordi Mukiele",         "DF", 79 },
    { "Lutsharel Geertruida",  "DF", 80 },
    { "Omar Alderete",         "DF", 76 },
    { "Arthur Masuaku",        "DF", 74 },
    { "James Tarkowski",       "DF", 80 },
    { "Jarrad Branthwaite",    "DF", 79 },
    { "Vitaliy Mykolenko",     "DF", 78 },
    { "Jake O'Brien",          "DF", 74 },
    { "Michael Keane",         "DF", 73 },
    { "Nathan Patterson",      "DF", 71 },
    { "Pedro Porro",           "DF", 82 },
    { "Micky van de Ven",      "DF", 82 },
    { "Cristian Romero",       "DF", 82 },
    { "Destiny Udogie",        "DF", 80 },
    { "Kevin Danso",           "DF", 79 },
    { "Ben Davies",            "DF", 75 },
    { "Radu Dragusin",         "DF", 75 },
    { "Antonee Robinson",      "DF", 79 },
    { "Calvin Bassey",         "DF", 76 },
    { "Joachim Andersen",      "DF", 79 },
    { "Kenny Tete",            "DF", 77 },
    { "Timothy Castagne",      "DF", 77 },
    { "Issa Diop",             "DF", 76 },
    { "Ryan Sessegnon",        "DF", 75 },
    { "Jorge Cuenca",          "DF", 75 },
    { "Maxim De Cuyper",       "DF", 80 },
    { "Ferdi Kadioglu",        "DF", 79 },
    { "Olivier Boscagli",      "DF", 79 },
    { "Jan Paul van Hecke",    "DF", 80 },
    { "Joel Veltman",          "DF", 77 },
    { "Lewis Dunk",            "DF", 77 },
    { "Adam Webster",          "DF", 75 },
    { "Marc Guehi",            "DF", 82 },
    { "Daniel Munoz",          "DF", 81 },
    { "Maxence Lacroix",       "DF", 79 },
    { "Tyrick Mitchell",       "DF", 78 },
    { "Chris Richards",        "DF", 77 },
    { "Borna Sosa",            "DF", 73 },
    { "Nathaniel Clyne",       "DF", 70 },
    { "Nathan Collins",        "DF", 79 },
    { "Sepp van den Berg",     "DF", 77 },
    { "Ethan Pinnock",         "DF", 77 },
    { "Keane Lewis-Potter",    "DF", 76 },
    { "Rico Henry",            "DF", 76 },
    { "Kristoffer Ajer",       "DF", 75 },
    { "Aaron Hickey",          "DF", 74 },
    { "Michael Kayode",        "DF", 73 },
    { "Bafode Diakite",        "DF", 79 },
    { "Marcos Senesi",         "DF", 78 },
    { "Adrien Truffert",       "DF", 77 },
    { "Julian Araujo",         "DF", 74 },
    { "Adam Smith",            "DF", 73 },
    { "Alex Jimenez",          "DF", 71 }
};

vector<player> GK = {      // ผู้รักษาประตู
    { "Alisson Becker",       "GK", 89 },
    { "David Raya",           "GK", 87 },
    { "Gianluigi Donnarumma", "GK", 89 },
    { "Robert Sanchez",       "GK", 78 },
    { "Senne Lammens",        "GK", 78 },
    { "Nick Pope",            "GK", 81 },
    { "Aaron Ramsdale",       "GK", 82 },
    { "Emiliano Martinez",    "GK", 87 },
    { "Robin Roefs",          "GK", 74 },
    { "Jordan Pickford",      "GK", 84 },
    { "Guglielmo Vicario",    "GK", 89 },
    { "Bernd Leno",           "GK", 82 },
    { "Bart Verbruggen",      "GK", 78 },
    { "Dean Henderson",       "GK", 81 },
    { "Caoimhin Kelleher",    "GK", 79 },
    { "Dorde Petrovic",       "GK", 73 }
};






// พิมพ์ต่อได้เรยจ้าาาา //





}
