#include <iostream>
#include <string>
#include <ctime>
#include <cstdlib>
using namespace std;

void ball[] = {Blackball , Goldball , silverball , bronzeball}
string FW[] = {"Mohamed Salah","Alexander Isak","Hugo Ekitiké","Cody Gakpo","Federico Chiesa","Viktor Gyökeres","Leandro Trossard","Kai Havertz","Gabriel Martinelli","Noni Madueke","Gabriel Jesus","Erling Haaland","Omar Marmoush","Phil Foden","Savinho","Rayan Cherki","Jérémy Doku","Oscar Bobb","João Pedro","Liam Delap","Raheem Sterling","Pedro Neto","Estêvão","Jamie Gittens","Bryan Mbeumo","Benjamin Šeško","Joshua Zirkzee","Anthony Gordon","Yoane Wissa","Jacob Murphy","Anthony Elanga","Harvey Barnes","Nick Woltemade","Jacob Ramsey","Ollie Watkins","John McGinn","Evann Guessand","Donyell Malen","Jadon Sancho","Brian Brobbey","Simon Adingra","Bertrand Traoré","Chemsdine Talbi","Wilson Isidor","Eliezer Mayenda","Romaine Mundle","Abdoullah Ba","Ian Poveda","Jack Grealish","Illiman Ndiaye","Dwight McNeil","Thierno Barry","Beto","Tyler Dibling","Randal Kolo Muani","Mohammed Judus","Dominic Solanke","Brennan Johnson","Richarlison","Mathys Tel","Wilson Odobert","Dane Scarlett","Dejan Kulusevski","Alex Iwobi","Samuel Chukwueze","Raúl Jiménez","Adama Traoré","Harry Wilson","Kevin","Rodrigo Muniz","Kaoru Mitoma","Danny Welbeck","Yankuba Minteh","Solly March","Charalampos Kostoulas","Stefanos Tzimas","Tom Watson","Jean-Philippe Mateta","Yeremy Pino","Chrisantus Uche","Eddie Nketiah","Jesurun Rak-Sakyi","Romain Esse","Kevin Schade","Dango Ouattara","Reiss Nelson","Igor Thiago","Myles Peart-Harris","Gustavo Nunes","Antoine Semenyo","Evanilson","Amine Adli","Enes Ünal","Marcus Tavernier","Romain Faivre","David Brooks","Eli Junior Krouli","Ben Doak"}; 

string MF[] = {"Florian Wirtz","Alexis Mac Allister","Ryan Gravenberch","Dominik Szoboszlai","Curtis Jones","Wataru Endo","Declan Rice","Martin Ødegaard","Mikel Merino","Zubimendi","Eberechi Eze","Rodri","Tijjani Reijinders","Bernardo Silva","Mateo Kovačić","Nico González","Kalvin Phillips","Cole Palmer","Moisés Caicedo","Enzo Fernández","Andrey Santos","Romeo Lavia","Alejandro Garnacho","Dário Essugo","Bruno Fernandes","Matheus Cunha","Casemiro","Manuel Ugarte","Amad","Kobbie Mainoo","Mason Mount","Bruno Guimarães","Sandro Tonali","Joelinton","Joe Willock","Youri Tielemans","Boubacar Kamara","Morgan Rogers","Amadou Onana","Harvey Elliot","Emiliano Buendía","Ross Barkley","Granit Xhaka","Habib Diarra","Enzo Le Fée","Noah Sadiki","Dan Neil","Chris Rigg","Idrissa Gueye","Kiernan Dewsbury-Hall","James Garner","Carlos Alcaraz","Merlin Röhl","Tim Iroegbunam","Xavi Simons","James Maddison","Palhinha","Rodrigo Bentancur","Pape Matar Sarr","Yves Bissouma","Lucas Bergvall","Archie Gray","Sander Berge","Saša Lukić","Emile Smith Rowe","Tom Cairney","Harrison Reed","Josh King","Carlos Baleba","Mats Wieffer","Georginio Rutter","Jack Hinshelwood","Yasin Ayari","Brajan Gruda","Diego Gómez","James Milner","Adam Wharton","Ismaïla Sarr","Jefferson Lerma","Daichi Kamada","Cheick Doucouré","Will Hughes","Justin Devenny","Naouirou Ahamada","Mikkel Damsgaard","Jordan Henderson","Mathias Jensen","Vitaly Janelt","Frack Onyeka","Fábio Carvalho","Antoni Milambo","Yehor Yarmoliuk","Ryan Christie","Tyler Adams","Lewis Cook","Justin Kluivert","Alex Scott"};

void DF[] =

void GK[] = 
